### ISSUE TITLE
Unable to start VM

### ISSUE THREAD

**Issue by mjcollin** [acislab/pragma-cloud-cluster#1]
Backfilling an issue from the ROCKS 6 installation attempt to re-test with 7:

I've made it up to trying to boot a vm cluster and I'm having trouble with I think the database of partitions on the head node. I'm starting with trying:

```
$ pragma boot biolinux 0 loglevel=DEBUG

...
  File "/opt/pragma_boot/pragma/utils.py", line 472, in get_gw 
   return self.nodes[node].get_gw() 
KeyError: 'pragma-vc-1'
```

That key is the reverse DNS name of the public interface. However I went to /var/log/pragma_boot/*.log and looked at all the commands that the log file says it's running and tried each in turn. This is the one that doesn't work:

```
$ /opt/rocks/bin/rocks add cluster 128.227.246.21 0 cpus-per-compute=1 mem-per-compute=2048 fe-name=pragma-vc-1 cluster-nam
ing=true vlan=1801 container-hosts=""

Error: could not find a partition on host (pcloud-head) to hold the VM's disk image
```

So I looked through the code and that's from https://github.com/rocksclusters/kvm/blob/431f01f1756684b6c4b4220178d9df8ff1726fb1/src/rocks-command/rocks/commands/add/host/vm/__init__.py which calls getLargestPartition() from https://github.com/rocksclusters/core/blob/0a5e256ffdf03d6119763bdb3d6f5b6fc961147e/src/rocks-pylib/rocks/vm.py​

I hacked that file in place to print out sizelist and host variables and this is what I got:

```
([], 'pcloud-head')
```

So I tried `rocks list host partition pcloud-head` which returns no partitions. `rocks list host partition` does list my head nodes partitions though.

**Comment by mjcollin** [comment]
The frontend partitions should be available by default. Any of this commands 
rocks list host partition
rocks list host partition localhost
rocks list host partition YOUR-FE-SHORT-NAME
should work

How did you do partitioning during install?
what is the output of  each above command and
of this 
rocks list cluster
rocks list host interface 

Does your frontend FQDN actually exist? You HAVE to HAVE DNS resolution for your frontend 
name and IP for the public interface

nadya

**Comment by mjcollin** [comment]
Re: ZFS setup
REPLYREPLY ALLFORWARD
Mark as unread

Williams, Nadya <nwilliams@ucsd.edu>
Tue 9/19/2017 7:00 PM
Archive
To:
Matthew Collins;
Cc:
Williams, Nadya <nwilliams@ucsd.edu>;
Smallen, Shava <ssmallen@sdsc.edu>;
You replied on 10/10/2017 6:10 PM.
HI matt,

i looked a bit around and your cluster exhibits a few problems. 
First, you don’t have partitions, then you also don’t have interfaces for the frontend.
Your routing is not quite right, some entries are missing, for example :
255.255.255.255 0.0.0.0         255.255.255.255 UH    0      0        0 eth0
224.0.0.0       0.0.0.0         255.255.255.0   U     0      0        0 eth0

Something went rather wrong during the install and your network is not correctly setup. 

In place of debugging i  would reinstall your frontend. This will be faster. 

Try to install the following rolls at the cluster install :
area51   
base 
ganglia
kernel
kvm
os
python

Once the frontend is up and running you can add zfs-linux and pragma-boot. 
I would export your zpool, This  would actually preserve it on the disks and then later on
after installing ifs roll on life fronted you can simply import it and  this will save time for rebuilding it. 

I don’t see anything inherently wrong in the logs but the absence of interfaces  is not good. 
partition is probably more benign   but owed not hurt to have it right. 

Area51 roll will be needed  for tripwire security checks, good to have on the frontend. 
Ganglia  can show the health of the cluster.

nadya

**Comment by mjcollin** [comment]
Regarding the "rocks list host partition" command, I reinstalled again with a single drive installed and can't get it to return a list of partitions on the head node. I've been through some of the rocks code and I can see that the partitions are definitly not inserted into the SQL database at install time, /tmp/db_partition_info.py ends up containing an empty array, but I can run methods from the RocksPartition class that enumerate the partitions and they work fine. I haven't found the middle part where they should get put in the database and there's no "rocks add partition" command so I can't manually fix it.​

**Comment by mjcollin** [comment]
Reproducing on ROCKS7. Initial install, output from partition listing commands:

```
[root@pcloud-head ~]# rocks list host partition
[root@pcloud-head ~]# rocks list host partition localhost
[root@pcloud-head ~]# rocks list host partition pcloud-head
[root@pcloud-head ~]# rocks list host
HOST              MEMBERSHIP   CPUS RACK RANK RUNACTION INSTALLACTION
pcloud-head:      Frontend     16   0    0    os        install 
```

After adding a vm container node:

```
[root@pcloud-head ~]# rocks list host partition vm-container-0-0
DEVICE MOUNTPOINT        START  SIZE   ID TYPE           FLAGS FORMATFLAGS
sda1   /                 1049kB 16.8GB -- ext4           boot  -----------
sda2   /var              16.8GB 4194MB -- ext4           ----- -----------
sda3   swap              21.0GB 1049MB -- linux-swap(v1) ----- -----------
sda4   ----------------- 22.0GB 138GB  -- -------------- ----- -----------
sda5   /state/partition1 22.0GB 138GB  -- ext4           ----- -----------
sdb    ----------------- ------ ------ -- -------------- ----- -----------
```

**Comment by mjcollin** [comment]
Still same error under ROCKS7:

```
[root@pcloud-head etc]# pragma boot biolinux 0 loglevel=DEBUG
Traceback (most recent call last):
  File "/opt/pragma_boot/bin/pragma", line 85, in <module>
    command.runWrapper(name, args[i:])
  File "/opt/pragma_boot/pragma/commands/__init__.py", line 1132, in runWrapper
    self.run(self._params, self._args)
  File "/opt/pragma_boot/pragma/commands/boot/__init__.py", line 152, in run
    if not(driver.allocate(num_cpus, memory, key, add_ifaces, repository)):
  File "/opt/pragma_boot/pragma/drivers/kvm_rocks/__init__.py", line 161, in allocate
    vc_out.write()
  File "/opt/pragma_boot/pragma/repository/processor/xmlprocessor.py", line 242, in write
    file.write(str(self))
  File "/opt/pragma_boot/pragma/repository/processor/xmlprocessor.py", line 119, in __str__
    'gw': self.network.get_gw(self.network.get_frontend())
  File "/opt/pragma_boot/pragma/utils.py", line 472, in get_gw
    return self.nodes[node].get_gw()
KeyError: 'pragma-vc-1'
```

Setting up HP server...

**Comment by mjcollin** [comment]
Installed on HP G7 server, same partitions output:

```
[root@pcloud-head ~]# rocks list host partition
[root@pcloud-head ~]# rocks list host partition localhost
[root@pcloud-head ~]# rocks list host partition pcloud-head
```

I don't believe this is the issue, will look at pragma boot code to figure out exactly what it's expecting the output of the partitions list to be and why.

**Comment by mjcollin** [comment]
/tmp/do_partition_info.py

```
RocksVersion = '7.0'
RocksRelease = 'Manzanita'
KickstartHost = '10.13.42.20'

import ConfigPartitions
app = ConfigPartitions.App()
app.setHostname('pcloud-head.acis.ufl.edu')
app.run()
```

```
PYTHONPATH=/tmp /opt/rocks/bin/python /opt/rocks/lib/python2.7/site-packages/rocks/record_partitions.py
```
